name: Does the library still build on all platforms?

on:
  push:
    paths:
      - '*'
      - '!docs/*'   # Don't run workflow when files are only in the docs directory
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build default features
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build parsing
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --fetures parsing
    - name: Build tester
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --fetures tester
    - name: Build parallel
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --fetures parallel
    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
        with:
          command: test
  wasm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    - name: Build for WASM
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target wasm32-unknown-unknown
