name: Do we still build on all supported platforms?

on:
  schedule:
    # Every Sunday, run this action
    - cron: '0 0 * * 0'
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build default features
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build parsing
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --features parsing
    - name: Build tester
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --features tester
    - name: Build parallel
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features --features parallel
    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
  wasm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    - name: Build for WASM
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target wasm32-unknown-unknown
  webview-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        default: true
    - name: Build for wasm
      run: cd docs/truth-tester-webview && cargo check --target wasm32-unknown-unknown
