name: Does the webview still build?

on:
  push:
    paths:
      - '*'
      - '!src/*'    # Don't run workflow when files are only in the src directory
jobs:
  webview-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        default: true
    - name: Build for wasm
      run: cd docs/truth-tester-webview && cargo check --target wasm32-unknown-unknown
