name: Does the webview still build?

on:
  push:
    paths:
      - '*'
      - '!src/*'    # Don't run workflow when files are only in the src directory
jobs:
  webview-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Default to nightly
      run: rustup default nightly
    - name: Add wasm Target
      run: rustup target add wasm32-unknown-unknown
    - name: Build for wasm
      run: cd docs/truth-tester-webview && cargo +nightly build --verbose --target wasm32-unknown-unknown
